//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Health.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class S4HealthEntities : DbContext
    {
        public S4HealthEntities()
            : base("name=S4HealthEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<S4anli> S4anli { get; set; }
        public DbSet<S4doctors> S4doctors { get; set; }
        public DbSet<S4huanjing> S4huanjing { get; set; }
        public DbSet<S4image> S4image { get; set; }
        public DbSet<S4information> S4information { get; set; }
        public DbSet<S4liuyan> S4liuyan { get; set; }
        public DbSet<S4machine> S4machine { get; set; }
        public DbSet<S4manager> S4manager { get; set; }
        public DbSet<S4news> S4news { get; set; }
        public DbSet<S4newstype> S4newstype { get; set; }
        public DbSet<S4orders> S4orders { get; set; }
        public DbSet<S4ordertype> S4ordertype { get; set; }
        public DbSet<S4text> S4text { get; set; }
        public DbSet<S4users> S4users { get; set; }
        public DbSet<S4xiangmu> S4xiangmu { get; set; }
        public DbSet<S4zhishi> S4zhishi { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<timetype> timetype { get; set; }
    }
}
