//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Health.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class S4liuyan
    {
        public int lid { get; set; }
        public Nullable<int> uid { get; set; }
        public Nullable<int> did { get; set; }
        public string utalk { get; set; }
        public string dtalk { get; set; }
    
        public virtual S4doctors S4doctors { get; set; }
        public virtual S4users S4users { get; set; }
    }
}
