//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Health.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class S4newstype
    {
        public S4newstype()
        {
            this.S4news = new HashSet<S4news>();
        }
    
        public int ntid { get; set; }
        public string ntname { get; set; }
    
        public virtual ICollection<S4news> S4news { get; set; }
    }
}
