//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Health.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class S4users
    {
        public S4users()
        {
            this.S4anli = new HashSet<S4anli>();
            this.S4liuyan = new HashSet<S4liuyan>();
            this.S4orders = new HashSet<S4orders>();
        }
    
        public int uid { get; set; }
        public string uname { get; set; }
        public string uacount { get; set; }
        public string upwd { get; set; }
        public string uphone { get; set; }
        public string img { get; set; }
        public Nullable<int> did { get; set; }
        public string uscore { get; set; }
    
        public virtual ICollection<S4anli> S4anli { get; set; }
        public virtual S4doctors S4doctors { get; set; }
        public virtual ICollection<S4liuyan> S4liuyan { get; set; }
        public virtual ICollection<S4orders> S4orders { get; set; }
    }
}
