//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Health.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class S4xiangmu
    {
        public S4xiangmu()
        {
            this.S4anli = new HashSet<S4anli>();
            this.S4doctors = new HashSet<S4doctors>();
            this.S4zhishi = new HashSet<S4zhishi>();
        }
    
        public int xid { get; set; }
        public string xname { get; set; }
        public string xjieshao { get; set; }
    
        public virtual ICollection<S4anli> S4anli { get; set; }
        public virtual ICollection<S4doctors> S4doctors { get; set; }
        public virtual ICollection<S4zhishi> S4zhishi { get; set; }
    }
}
