//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Health.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class timetype
    {
        public timetype()
        {
            this.S4doctors = new HashSet<S4doctors>();
            this.S4orders = new HashSet<S4orders>();
        }
    
        public int tiid { get; set; }
        public string tiname { get; set; }
    
        public virtual ICollection<S4doctors> S4doctors { get; set; }
        public virtual ICollection<S4orders> S4orders { get; set; }
    }
}
